CHANGELOG.md
config/ftbquests/quests/chapters/0095002B3E34FD9A.snbt
config/ftbquests/quests/chapters/0E9796448AFA83CD.snbt
config/ftbquests/quests/chapters/3676C6A060A63447.snbt
config/ftbquests/quests/chapters/777EE0C4949DFE12.snbt
config/ftbquests/quests/lang/en_us.snbt
config/ftbquests/quests/reward_tables/2806F6BEA4A73B0B.snbt

Quest continuation

---

kubejs/server_scripts/loot_tables/blocks/minecraft/reinforced_deepslate.js
kubejs/server_scripts/tags/block/minecraft/mineable.js
kubejs/server_scripts/tags/block/minecraft/needs_iron_tool.js

Make Reinforced Deepslate breakable 
Quick addition for the release if time permits

Make Reinforced Deepslate breakable

---

CHANGELOG.md
kubejs/server_scripts/constants/unification.js
kubejs/server_scripts/loot_tables/chests/aquaculture/treasure_chest.js
kubejs/server_scripts/recipes/enigmatica/sawing.js
kubejs/server_scripts/recipes/modern_industrialization/mixer.js

- Fix some broken tags and kubejs errors

kube errors

---

CHANGELOG.md
kubejs/server_scripts/recipes/mekanism/enriching.js
kubejs/server_scripts/recipes/mekanism/metallurgic_infusing.js

Restore mekanism recipes

---

CHANGELOG.md
config/Mekanism/general.toml
config/Mekanism/generators.toml
kubejs/server_scripts/recipes/modern_industrialization/assembler.js
kubejs/server_scripts/tags/item/modern_industrialization/crushed_dust.js
kubejs/server_scripts/tags/item/modern_industrialization/replicator_blacklist.js

-   Cheaper scaling of many MI components. Bonus for crafting via Assembler
- Adds some tags for filtering crushed dusts https://github.com/EnigmaticaModpacks/Enigmatica10/issues/115

cheaper MI components

---

CHANGELOG.md
kubejs/server_scripts/recipes/enigmatica/sawing.js

- Otherworld logs can now be sawed in various machines

Compatibility

---

CHANGELOG.md
kubejs/server_scripts/recipes/ars_additions/locate_structure.js

fix broken stronghold locator

---

kubejs/server_scripts/tags/item/neoforge/crops.js
kubejs/server_scripts/tags/item/neoforge/seeds.js

Fix a few crop tags for IF to work with them

crop tag fixes

---

CHANGELOG.md
config/almostunified/placeholders.json
kubejs/server_scripts/recipes/ars_nouveau/imbuement.js
kubejs/server_scripts/recipes/industrialforegoing/dissolution_chamber.js

Fluix may be crafted with IF now.
Source gem blocks now provide a source discount over individual source gems

More recipe additions

---

CHANGELOG.md
config/almostunified/placeholders.json
kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/enigmatica/remove.js
kubejs/server_scripts/recipes/enigmatica/replace_input.js
kubejs/server_scripts/recipes/occultism/crushing.js

- Convert SagMill recipes to appropriate unified outputs
- Add recipes to crush other mod ores/raw/ingots
- More compat between eio and ae2
- leads and sticky pistons craftable with pink slime now

Enderio Compat Recipes

---

CHANGELOG.md
config/occultism-server.toml
kubejs/server_scripts/recipes/occultism/ritual.js
kubejs/server_scripts/tags/entity_type/neoforge/capturing_not_supported.js

- Swap occultism ritual time reduction over to the mod's config. Had forgotten it.

Smol Fixes

---

CHANGELOG.md
kubejs/server_scripts/recipes/ars_nouveau/shapeless.js
kubejs/server_scripts/recipes/enigmatica/remove.js
kubejs/server_scripts/recipes/enigmatica/shapeless.js
kubejs/server_scripts/recipes/handcrafted/shaped.js

-   Fix recipe conflict with Sulfur/dye conversion 
- Fix Sourcestone button recipe conflict
-   Fix recipe conflict with Terracotta Thin Pots

Fix Recipe Conflicts

---

CHANGELOG.md
config/ftbquests/quests/chapters/25ADADD36B4FDE05.snbt
config/ftbquests/quests/chapters/27C4C213A1A05E6E.snbt
config/ftbquests/quests/chapters/2F5B4621D5F0381A.snbt
config/ftbquests/quests/chapters/4D1E38918B64CD4E.snbt
config/ftbquests/quests/chapters/7F17CDF8564DCC49.snbt
config/ftbquests/quests/chapters/ender_io.snbt
config/ftbquests/quests/chapters/industrial_foregoing.snbt
config/ftbquests/quests/chapters/pneumaticcraft.snbt
config/ftbquests/quests/lang/en_us.snbt
config/ftbquests/quests/reward_tables/4C3908A1EDE782F7.snbt
kubejs/server_scripts/recipes/enderio/shaped.js
kubejs/server_scripts/recipes/enigmatica/shaped.js
kubejs/server_scripts/recipes/industrialforegoing/shaped.js
kubejs/server_scripts/recipes/modern_industrialization/shaped.js
kubejs/server_scripts/recipes/pneumaticcraft/shaped.js

Just a basic start to get people going. More quests will follow, of course. 
Also adds some bonus output to gears covered by PNC, IF, and Ender IO. They were in a weird spot, particularly Iron Gears, which are added by three different mods with three very different recipes. I'll leave the MI recipes as they are for now, but I've taken the Ender IO default recipe and made it output 2 gears instead of 1. 
This way if you do decide to go that route, you can get a discount. 
Similarly, gold, diamond, and compressed iron can all get a discount using similar recipes

Basic EIO and IF quests

---

config/ftbquests/quests/chapters/ender_io.snbt
config/ftbquests/quests/chapters/industrial_foregoing.snbt
config/ftbquests/quests/lang/en_us.snbt

More IF quests

---

kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/mekanism/reaction.js

fixes lack of unification for mekanism PRC. Reverts changes to unify Enderio as that's fixed in AU now.

revert temp enderio fix, apply temp mekanism fix

---

kubejs/server_scripts/recipes/geneticsresequenced/genetics.js

format changed on these recently

fix custom genes

---

defaultconfigs/emi.css

Disables batched rendering to avoid conflict with iris.

default emi configs

---

CHANGELOG.md
config/almostunified/placeholders.json
config/ftbquests/quests/chapters/402AE6264B81A84B.snbt
config/ftbquests/quests/chapters/actually_additions.snbt
config/ftbquests/quests/lang/en_us.snbt
kubejs/client_scripts/emi/world_interactions.js
kubejs/server_scripts/constants/beheading_tools.js
kubejs/server_scripts/recipes/actuallyadditions/coffee_ingredient.js
kubejs/server_scripts/recipes/actuallyadditions/crushing.js
kubejs/server_scripts/recipes/ars_nouveau/budding_conversion.js
kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/enigmatica/remove.js
kubejs/server_scripts/recipes/farmingforblockheads/market.js
kubejs/server_scripts/recipes/industrialforegoing/laser_drill_ore.js
kubejs/server_scripts/recipes/mekanism/enriching.js
kubejs/server_scripts/recipes/modern_industrialization/centrifuge.js
kubejs/server_scripts/recipes/modern_industrialization/chemical_reactor.js
kubejs/server_scripts/recipes/modern_industrialization/distillery.js
kubejs/server_scripts/recipes/modern_industrialization/fluid_fuels.js
kubejs/server_scripts/recipes/modern_industrialization/mixer.js
kubejs/server_scripts/recipes/occultism/crushing.js
kubejs/server_scripts/recipes/occultism/miner.js
kubejs/server_scripts/recipes/pneumaticcraft/fuel_quality.js
kubejs/server_scripts/recipes/pneumaticcraft/thermo_plant.js
kubejs/server_scripts/tags/fluids/neoforge/plantoil.js

-   Amethyst Golems now convert Certus straight to Flawless
- More crushing compat https://github.com/EnigmaticaModpacks/Enigmatica10/issues/182
- AA quests!
- More fuel compat!
- Coffee effects have been buffed and expanded upon

Quest work and general tweaks

---

kubejs/startup_scripts/better_stacks.js

revert soul gem stacks

---

CHANGELOG.md
kubejs/server_scripts/recipes/actuallyadditions/crushing.js
kubejs/server_scripts/recipes/ars_nouveau/crushing.js

fix lignite crushing

---

CHANGELOG.md
kubejs/server_scripts/tags/item/minecraft/enchantable.js

- Allow wolf armor to be enchanted

Allow wolf armor to be enchanted

---

CHANGELOG.md
kubejs/server_scripts/recipes/theurgy/calcination.js
kubejs/server_scripts/recipes/theurgy/distillation.js

These machines tend to need spamming in order to do much with the mod. This just reduces that spam by speeding up calcination and distillation

buff theurgy salt and mercury production

---

CHANGELOG.md
kubejs/server_scripts/recipes/minecraft/compostable.js

-   Gysahl Greens are now compostable

Gysahl Greens are now compostable 

---

CHANGELOG.md
config/almostunified/placeholders.json
config/almostunified/unification/materials.json

These are on the chopping block for EIO but who knows when. Considering they don't quite work with everything dyes do, I'm just unifying them out of existence.

Unify EIO's Organic Dyes

---

CHANGELOG.md
kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/enigmatica/replace_input.js

Also so input replacements for Pretty Pipes when that goes in

Fix EIO Sag milling

---

kubejs/server_scripts/recipes/ppfluids/shaped.js
kubejs/server_scripts/recipes/ppfluids/shapeless.js

dunno how long it's gonna take ppfluids to fix their recipes, so I have just copied what they have in code and re-made them in the interest of getting another release out soonish. Lots of big changes and mod updates.

temp recipes for ppfluids

---

CHANGELOG.md
config/ftbquests/quests/chapters/0E9796448AFA83CD.snbt
config/ftbquests/quests/chapters/402AE6264B81A84B.snbt
config/ftbquests/quests/lang/en_us.snbt
config/ftbquests/quests/reward_tables/4C3908A1EDE782F7.snbt

pretty pipes quests

---

CHANGELOG.md
kubejs/server_scripts/tags/item/minecraft/enchantable.js

Fix JDT Bow enchantability https://github.com/EnigmaticaModpacks/Enigmatica10/issues/212

Fix JDT Bow enchantability

---

kubejs/server_scripts/tags/block/neoforge/storage_blocks.js
kubejs/server_scripts/tags/item/neoforge/clumps.js
kubejs/server_scripts/tags/item/neoforge/dusts.js
kubejs/server_scripts/tags/item/neoforge/gems.js
kubejs/server_scripts/tags/item/neoforge/ingots.js
kubejs/server_scripts/tags/item/neoforge/storage_blocks.js
kubejs/server_scripts/tags/item/neoforge/tiny_clumps.js
kubejs/server_scripts/tags/item/oritech/machine_addons.js
kubejs/server_scripts/tags/item/oritech/machine_cores.js

Oritech Integration

---

kubejs/server_scripts/recipes/enigmatica/replace_input.js

re-enable biosteel in oritech recipes

Oritech compat

---

config/ftbquests/quests/chapters/oritech.snbt
config/ftbquests/quests/lang/en_us.snbt
config/ftbquests/quests/reward_tables/304C87B452C4DF86.snbt

Oritech quests

---

CHANGELOG.md
kubejs/server_scripts/recipes/actuallyadditions/crushing.js
kubejs/server_scripts/recipes/ars_nouveau/crushing.js

black dye crushing

---

kubejs/server_scripts/recipes/oritech/atomic_forge.js
kubejs/server_scripts/recipes/oritech/grinder.js
kubejs/server_scripts/recipes/oritech/pulverizer.js

buffs ore processing a bit. allows for the creation of emerald

oritech processing buffs

---

kubejs/server_scripts/recipes/oritech/pulverizer.js

fix oritech sandstone crushing

---

kubejs/server_scripts/recipes/oritech/deep_drill.js

fix deep drill recipe ids

---

kubejs/server_scripts/recipes/oritech/grinder.js
kubejs/server_scripts/recipes/oritech/pulverizer.js

fix erroring oritech ore processing recipes

fix erroring oritech ore processing recipes

---

CHANGELOG.md
kubejs/server_scripts/recipes/oritech/assembler.js
kubejs/server_scripts/recipes/oritech/atomic_forge.js
kubejs/server_scripts/recipes/oritech/pulverizer.js

Add missing Silicon recipes to the Assembler and Atomic Forge

Smoll Fixes

---

CHANGELOG.md
kubejs/server_scripts/constants/stoneworks.js
kubejs/server_scripts/recipes/actuallyadditions/crushing.js
kubejs/server_scripts/recipes/ars_nouveau/crushing.js
kubejs/server_scripts/recipes/cobblegengalore/blockgen.js
kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/enigmatica/remove.js
kubejs/server_scripts/recipes/enigmatica/simple_crushing.js
kubejs/server_scripts/recipes/industrialforegoing/dissolution_chamber.js
kubejs/server_scripts/recipes/mekanism/crushing.js
kubejs/server_scripts/recipes/mekanism/enriching.js
kubejs/server_scripts/recipes/modern_industrialization/assembler.js
kubejs/server_scripts/recipes/modern_industrialization/electrolyzer.js
kubejs/server_scripts/recipes/modern_industrialization/macerator.js
kubejs/server_scripts/recipes/modern_industrialization/mixer.js
kubejs/server_scripts/recipes/modern_industrialization/packer.js
kubejs/server_scripts/recipes/naturesaura/altar.js
kubejs/server_scripts/recipes/occultism/crushing.js
kubejs/server_scripts/recipes/oritech/assembler.js
kubejs/server_scripts/recipes/oritech/atomic_forge.js
kubejs/server_scripts/recipes/oritech/grinder.js
kubejs/server_scripts/recipes/oritech/pulverizer.js
kubejs/server_scripts/recipes/pneumaticcraft/assembly.js
kubejs/server_scripts/recipes/pneumaticcraft/pressure_chamber.js
kubejs/server_scripts/tags/item/neoforge/dye_materials.js

Unifying simple crushing recipes under a single script. 
Add support for Aether stones to Cobblegen Galore
Add support for new AE processors in PNC, MI, and Oritech

Simple Crushing and overlooked integration

---

config/curios-common.toml

revert accidental curios change in #279

revert accidental curios change in #279

---

CHANGELOG.md
config/ftbquests/quests/chapters/oritech.snbt
config/ftbquests/quests/lang/en_us.snbt

missed pushes from #281

---

CHANGELOG.md
kubejs/server_scripts/recipes/oritech/grinder.js
kubejs/server_scripts/recipes/oritech/pulverizer.js
kubejs/server_scripts/tags/item/neoforge/dye_materials.js

so it truly replaces the pulverizer when it's craftable

Add more parity recipes to the Fragment Forge 

---

CHANGELOG.md
kubejs/server_scripts/recipes/oritech/particle_collision.js

Crying obsidian recipe via Oritech

Crying obsidian recipe via Oritech

---

config/ftbquests/quests/lang/en_us.snbt

I am assuming this was a typo.

Logisticss -> Logistics

---

CHANGELOG.md
kubejs/server_scripts/tags/item/neoforge/seeds.js

https://github.com/EnigmaticaModpacks/Enigmatica10/issues/293

fix wheat not appearing in sprig output

---

CHANGELOG.md
kubejs/server_scripts/recipes/modern_industrialization/assembler.js

Remove duplicate MI upgrade recipe

Remove duplicate MI upgrade recipe

---

CHANGELOG.md
kubejs/server_scripts/recipes/modern_industrialization/mixer.js

Resolves https://github.com/EnigmaticaModpacks/Enigmatica10/issues/309

JDT Fuel crafting fix

---

CHANGELOG.md
config/ftbquests/quests/lang/en_us.snbt

Resolves https://github.com/EnigmaticaModpacks/Enigmatica10/issues/311

Fix typo in MI quests

---

kubejs/server_scripts/recipes/naturesaura/animal_spawner.js

Add chocobo to the altar of birthing

---

kubejs/server_scripts/recipes/occultism/pentacles.js
kubejs/server_scripts/tags/item/ae2/can_remove_color.js

- further pentacle updates. No player visible changes, just tag updates
- soap can clean ae2 cables

More integrations

---

kubejs/server_scripts/recipes/oritech/particle_collision.js

Changes to collision calculation appear to have made these recipes quite a bit more difficult than intended.

reduce upper limit particle accelerator speeds

---

kubejs/server_scripts/recipes/oritech/cooler.js

was added by Oritech by default

remove duplicate snow recipe

---

kubejs/server_scripts/recipes/enigmatica/remove.js

Oritech changed a few recipes here. Correcting our recipes as a result.

Fix sandstone grinding

---

CHANGELOG.md
kubejs/server_scripts/recipes/enigmatica/replace_input.js
kubejs/server_scripts/recipes/industrialforegoing/laser_drill_ore.js
kubejs/server_scripts/recipes/oritech/particle_collision.js
kubejs/server_scripts/tags/block/neoforge/ores.js
kubejs/server_scripts/tags/block/neoforge/storage_blocks.js
kubejs/server_scripts/tags/item/neoforge/ingots.js
kubejs/server_scripts/tags/item/neoforge/ores.js
kubejs/server_scripts/tags/item/neoforge/raw_materials.js
kubejs/server_scripts/tags/item/neoforge/storage_blocks.js

Tags! Buuz!
Adds very minor gating to Theurgy and Replication such that you'll need to have done at least some basic tasks in Magic or Tech mods, respectively, to get to full on resource duplication.
Raw Replica may be obtained through Laser Drill or Particle Acceleration

Replication Integration

---

config/ftbquests/quests/reward_tables/72C4CB45CED49659.snbt
kubejs/server_scripts/item_events/tooltips.js

corrects the way NA's loot chest is displayed
adds ender storage to dimensional storage tooltips

tooltips and quest corrections

---

CHANGELOG.md
config/ftbquests/quests/lang/en_us.snbt
kubejs/startup_scripts/better_stacks.js

Thanks to Dravster for the additions!

Update Better Stacks

---

kubejs/server_scripts/recipes/modern_industrialization/assembler.js

removes a duplicate circuit recipe

mi recipe duplicate

---

config/ftbquests/quests/chapters/402AE6264B81A84B.snbt
config/ftbquests/quests/lang/en_us.snbt
kubejs/server_scripts/recipes/enigmatica/simple_crushing.js

Just adds a question mention in the Logistics chapter and adds machine recipes for crushing redstone blocks to flux dust

flux networks integration

---

CHANGELOG.md
kubejs/server_scripts/recipes/minecraft/blasting.js

allow blocks of raw ore to be smelted directly https://github.com/EnigmaticaModpacks/Enigmatica10/issues/372

raw block smelting

---

CHANGELOG.md
kubejs/server_scripts/recipes/modern_industrialization/cutting_machine.js

They were conflicting with MI Bolt recipes.

Remove MI AE2 Cable Anchor Recipes

---

CHANGELOG.md
kubejs/server_scripts/functions.js
kubejs/server_scripts/recipes/bigreactors/fluidizer.js
kubejs/server_scripts/recipes/bigreactors/reprocessor.js
kubejs/server_scripts/tags/block/neoforge/storage_blocks.js
kubejs/server_scripts/tags/item/neoforge/storage_blocks.js

Re-adds a few recipes that are missing as a result of unification

fix recipes that aren't being unified

---

CHANGELOG.md
config/almostunified/unification/materials.json
kubejs/server_scripts/constants/stoneworks.js
kubejs/server_scripts/loot_tables/blocks/modern_industrialization/bauxite_ore.js
kubejs/server_scripts/loot_tables/blocks/modern_industrialization/deepslate_bauxite_ore.js
kubejs/server_scripts/recipes/actuallyadditions/crushing.js
kubejs/server_scripts/recipes/ars_nouveau/crushing.js
kubejs/server_scripts/recipes/cobblegengalore/blockgen.js
kubejs/server_scripts/recipes/enderio/alloy_smelting.js
kubejs/server_scripts/recipes/enderio/sag_milling.js
kubejs/server_scripts/recipes/extended_industrialization/alloy_smelter.js
kubejs/server_scripts/recipes/industrialforegoing/dissolution_chamber.js
kubejs/server_scripts/recipes/industrialforegoing/laser_drill_ore.js
kubejs/server_scripts/recipes/mekanism/enriching.js
kubejs/server_scripts/recipes/modern_industrialization/macerator.js
kubejs/server_scripts/recipes/modern_industrialization/quarry.js
kubejs/server_scripts/recipes/oritech/deep_drill.js
kubejs/server_scripts/recipes/oritech/grinder.js
kubejs/server_scripts/recipes/oritech/pulverizer.js
kubejs/server_scripts/recipes/replication/matter_values.js

- Create stones are added to Cobblegens. Enjoy the free resources
- IE Bauxite processing has been added to more machines
- Oritech now produces Raw Bauxite instead of MI's Crushed Bauxite
- MI Bauxite Ore now drops Raw Bauxite when mined instead of Bauxite Dust

IE and Create Ore integrations

---

CHANGELOG.md
config/ftbquests/quests/chapters/0095002B3E34FD9A.snbt
config/ftbquests/quests/reward_tables/3DDCF3026E8E3D91.snbt
config/ftbquests/quests/reward_tables/4C3908A1EDE782F7.snbt
config/ftbquests/quests/reward_tables/72C4CB45CED49659.snbt

-   Occultism quests now mention Tuff Bricks as a requirement for Aviar's

add a note about tuff bricks in the quests for occultism

---

config/almostunified/unification/materials.json
kubejs/server_scripts/recipes/enigmatica/remove.js

This just removes some duplicate recipes from Oritech in newer versions.

cleanup for new oritech recipes

---

CHANGELOG.md
kubejs/server_scripts/tags/item/accessories/accessories.js

Fix issue with curios getting lost in hidden accessories slots

Fix issue with curios getting lost in hidden accessories slots

---

kubejs/server_scripts/recipes/malum/reaping_data.js
kubejs/server_scripts/recipes/malum/spirit_data.js

Adds Spirit and Reaping compat to various other mobs in the pack.

Malum integration

---

config/ftbquests/quests/chapters/402AE6264B81A84B.snbt
config/ftbquests/quests/lang/en_us.snbt

Transfer Labels Quests

---

CHANGELOG.md
kubejs/client_scripts/emi/world_interactions.js
kubejs/server_scripts/recipe_viewer/info.js
kubejs/server_scripts/recipes/create/deploying.js
kubejs/server_scripts/recipes/create/sequenced_assembly.js
kubejs/server_scripts/recipes/immersiveengineering/blueprint.js
kubejs/server_scripts/recipes/immersiveengineering/crusher.js
kubejs/server_scripts/recipes/immersiveengineering/metal_press.js
kubejs/server_scripts/recipes/oritech/particle_collision.js
kubejs/server_scripts/tags/item/minecraft/enchantable.js
kubejs/startup_scripts/better_stacks.js

Adds a couple ae2/ie compat recipes

IE + AE compat

---

kubejs/server_scripts/recipes/enigmatica/blasting.js
kubejs/server_scripts/recipes/enigmatica/smelting.js

likely got removed in recent unification efforts, re-adding.

re-add missing smelting recipes
